### PR TITLE
Adding d3 bar chart sample. Using Fable 0.7.

### PR DESCRIPTION
**Pull request by leolorenzoluis**

### CODE REVIEW

**Comment by MangelMaxime** [comment]
We will wait for #7 to be accepted/finish before merging this one. :)

**Comment by leolorenzoluis** [comment]
I've merged the files with the latest changes.

**Comment by MangelMaxime** [comment]
Thank you for this new sample :)
If you want to propose new samples you can see my little modifications in this commit: http://github.com/fable-compiler/fable-graphics/commit/1dfb4737998c972f4cdbfec1cb4904ddcf29f29b

This is to allow using shared deps for all the samples + Fixing the sample to a div for a better display in the live sample. [Live version](http://fable.io/fable-graphics/samples/d3/barchart/index.html)

**Comment by whitetigle** [comment]
The sample is indeed great!

**Pull request merged**
